### ISSUE TITLE
A couple of clarification on the step

### ISSUE THREAD

**Issue by ayuwono** [wooldridge/ml-certauth#1]
Hi Mike,

Here a couple of steps that will make the example steps more clear to the user:

After running:
openssl pkcs12 -export -in portal.cer -inkey portalpriv.pkey -out portaltest.pfx
It will as Export password. Put 'p' as the password

On "At the bottom, click Show and check the Acme Corp checkbox. Click OK to save."
It should be: "At the bottom, click Show, click Acme Corp, and check the checkbox. Click OK to save."

Thanks,
Aries

**Comment by wooldridge** [comment]
Thanks, @ayuwono. Fixed with: https://github.com/wooldridge/ml-certauth/commit/dc027907984517631e7c0f86acda487f00641764
